services:
  app:
    container_name: atr
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount your local workspace into the container.
      - ..:/home/ubuntu/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - "8000:8000"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
    # Keep the container alive for VS Code to attach
    command: sleep infinity
  # The InfluxDB 3 core service
  # The Eclipse Mosquitto MQTT broker service
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ../config/mosquitto/config:/mosquitto/config
      - ../config/mosquitto/data:/mosquitto/data
      - ../config/mosquitto/log:/mosquitto/log
